### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [felfert/sslutils#1]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 248: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 248: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 275: API name => Cipher:First parameter (with value "DES/CBC/NoPadding") should be any of {AES, Blowfish, DESede, PBEWithHmacSHA224AndAES_128, PBEWithHmacSHA256AndAES_128, PBEWithHmacSHA384AndAES_128, PBEWithHmacSHA512AndAES_128, PBEWithHmacSHA224AndAES_256, PBEWithHmacSHA256AndAES_256, PBEWithHmacSHA384AndAES_256, PBEWithHmacSHA512AndAES_256, RSA}<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 280: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 264: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 251: API name => Cipher:First parameter (with value "AES/CBC/NoPadding") should be any of AES/CBC/{Empty String, PKCS7Padding, PKCS5Padding, ISO10126Padding}<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 243: API name => Cipher:First parameter (with value "AES/CBC/NoPadding") should be any of AES/CBC/{Empty String, PKCS7Padding, PKCS5Padding, ISO10126Padding}<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 256: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 330: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 259: API name => Cipher:First parameter (with value "AES/CBC/NoPadding") should be any of AES/CBC/{Empty String, PKCS7Padding, PKCS5Padding, ISO10126Padding}<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 286: API name => Cipher:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 286: API name => Cipher:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 267: API name => Cipher:First parameter (with value "DESede/CBC/NoPadding") should be any of DESede/CBC/{Empty String, PKCS7Padding, PKCS5Padding, ISO10126Padding}<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 285: API name => IvParameterSpec:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 345: API name => MessageDigest:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 264: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 272: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 280: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 256: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/felfert/sslutils/PEMDecoder.java: Line number => 272: API name => SecretKeySpec:<BR>

**Comment by felfert** [comment]
Running some automated code analysis tool without actually understanding it, is bad practice.
